import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#87ceeb',
    },
    imagem: {
        flex: 1,
        width: '100%',
      },
    box: {
        marginTop: 25,
        marginBottom: 25,
        alignItems:'center',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    boxtitulo: {
        backgroundColor: 'white',
        height: 85,
        width: '100%',
        margin: 'auto',
    },
    titulo: {
        textAlign: 'center',
        fontSize: 40,
        color: '#6745d0',
        fontWeight: 'bold',
        paddingTop: 20,
        padding: 5,
    },
    texto: {
        fontSize: 25,
        color: 'white',
        marginTop: 20,
        textAlign: 'center',
    },
    texto2: {
        fontSize: 15,
        color: 'white',
        textAlign: 'justify',
        marginLeft: 20,
        marginRight: 20,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
        padding: 10,

    },
    texto3: {
        fontSize: 45,
        color: 'white',
        marginTop: 20,
        textAlign: 'center',
    },
    borda:{
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
        padding: 5,
        borderRadius: 10/2,
        marginRight: 10,
        marginLeft: 10,
    },
    box1:{
        backgroundColor: '#DEA39C',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box2:{
        backgroundColor: '#EFB661',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box3:{
        backgroundColor: '#FFB549',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box4:{
        backgroundColor: '#A0D1CA',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box5:{
        backgroundColor: '#CDA7C1',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box6:{
        backgroundColor: '#F9423A',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      box7:{
        backgroundColor: '#6B8F9C',
        height: 650,
        width: 300,
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: 'white',
      },
      image:{
        width: 250, 
        height: 250,
        marginLeft: 'auto', 
        marginRight: 'auto', 
        marginTop: 30, 
        marginBottom: 15,
        borderRadius: 50/2,
      }
})

export { styles };
